In [1]:
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
a=[[1,2,3],[4,5,6],[7,8,9]]

In [3]:
A=np.array(a)

In [4]:
A.ndim

2

In [5]:
A.shape

(3, 3)

In [6]:
A.size

9

In [7]:
A[1][2]

6

In [8]:
A[1,2]

6

In [9]:
A[0][0:2]

array([1, 2])

In [10]:
A[0,0:2]

array([1, 2])

In [11]:
X=np.array([[1,0],[0,1]]) 
Y=np.array([[2,1],[1,2]])

In [12]:
Z=X+Y
Z

array([[3, 1],
       [1, 3]])

In [14]:
Z=2*Y
Z

array([[4, 2],
       [2, 4]])

In [16]:
Z=X*Y
Z

array([[2, 0],
       [0, 2]])

In [19]:
Z=np.dot(X,Y)
Z

array([[2, 1],
       [1, 2]])

In [20]:
np.sin(Z)

array([[0.90929743, 0.84147098],
       [0.84147098, 0.90929743]])

In [21]:
Z.T

array([[2, 1],
       [1, 2]])

In [22]:
C=np.array([[1,1],[2,2],[3,3]])

In [23]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])